{
 "title": "Solar Stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Daily Energy Production",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TodaysEnergy\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Today\"}))\n  |> yield(name: \"mean\")\n"
    },
    {
     "query": "import \"date\"\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: date.sub(d:24h, from:v.timeRangeStart), stop: date.sub(d:24h, from:v.timeRangeStop))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TodaysEnergy\")\n  |> timeShift(duration: 24h)\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Yesterday\"}))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Meters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"mqtt_electric_meter_reading\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Electric\"}))\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"home_assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"entity_id\"] == \"mqtt_gas_meter_reading\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccf\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Gas\"}))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Logger Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"delta-solar-tracker\"} "
    }
   ]
  },
  {
   "title": "Today's Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TodaysEnergy\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Today\"}))\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Current System Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 } },
  {
   "title": "Daily Production History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\" \noption location = timezone.location(name: \"America/Denver\")\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: -90d)\n  |> filter(fn: (r) => r._measurement == \"inverter_data\" and (r._field == \"TodaysEnergy\" and r._value >= 0))\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> group()\n  |> sort(columns: [\"_time\"], desc: false)\n  |> timeShift(duration: -12h, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> keep(columns:[\"_time\", \"_value\", \"_field\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Monthly Production History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\" \noption location = timezone.location(name: \"America/Denver\")\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: -2y)\n  |> filter(fn: (r) => r._measurement == \"inverter_data\" and (r._field == \"TodaysEnergy\" and r._value >= 0))\n  |> aggregateWindow(every: 1d, fn: last)\n  |> group()\n  |> sort(columns: [\"_time\"], desc: false)\n  |> timeShift(duration: -6h)\n  |> aggregateWindow(every: 1mo, fn: sum)\n  |> timeShift(duration: -1d)\n  |> group()"
    }
   ]
  },
  {
   "title": "Lifetime Production",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\" \noption location = timezone.location(name: \"America/Denver\")\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: 2021-01-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"inverter_data\" and (r._field == \"TodaysEnergy\" and r._value >= 0))\n  |> drop(columns: [\"model\"])\n  |> aggregateWindow(every: 1d, fn: last)\n  |> cumulativeSum()\n  |> rename(columns: {_field: \"Lifetime Production\"})\n  |> map(fn: (r) => ({ _value: r._value / 1000.0 , _time: r._time}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Daily Production History ($)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "import \"timezone\" \n\noption location = timezone.location(name: \"America/Denver\")\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: -90d)\n  |> filter(fn: (r) => r._measurement == \"inverter_data\" and (r._field == \"TodaysEnergy\" and r._value >= 0))\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> group()\n  |> sort(columns: [\"_time\"], desc: false)\n  |> timeShift(duration: -12h, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> rename(columns: {_field: \"Daily Production\"})\n  |> map(fn: (r) => ({ _value: r._value * 0.134 , _time: r._time }))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"]) "
    }
   ]
  },
  {
   "title": "Monthly Production History ($)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "import \"timezone\" \n\noption location = timezone.location(name: \"America/Denver\")\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: -2y)\n  |> filter(fn: (r) => r._measurement == \"inverter_data\" and (r._field == \"TodaysEnergy\" and r._value >= 0))\n  |> drop(columns: [\"model\"])\n  |> aggregateWindow(every: 1d, fn: last)\n  |> sort(columns: [\"_time\"], desc: false)\n  |> timeShift(duration: -6h)\n  |> aggregateWindow(every: 1mo, fn: sum)\n  |> timeShift(duration: -1d)\n  |> rename(columns: {_field: \"Monthly Production\"})\n  |> map(fn: (r) => ({ _value: r._value * 0.134 , _time: r._time }))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  "
    }
   ]
  },
  {
   "title": "Lifetime Production ($)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\" \noption location = timezone.location(name: \"America/Denver\")\n\nfrom(bucket: \"solar_stats/autogen\")\n  |> range(start: 2021-01-01T00:00:00Z)\n  |> filter(fn: (r) => r._measurement == \"inverter_data\" and (r._field == \"TodaysEnergy\" and r._value >= 0))\n  |> drop(columns: [\"model\"])\n  |> aggregateWindow(every: 1d, fn: last)\n  |> cumulativeSum()\n  |> rename(columns: {_field: \"Lifetime Production\"})\n  |> map(fn: (r) => ({ _value: r._value * 0.134, _time: r._time }))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  "
    }
   ]
  },
  {
   "title": "String Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PV1Voltage\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"West\"}))"
    },
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PV2Voltage\" or r[\"_field\"] == \"PV3Voltage\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \"East\": (r.PV2Voltage + r.PV3Voltage)/2.0 }))\n  |> keep(columns:[\"_time\", \"East\"])"
    }
   ]
  },
  {
   "title": "String Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PV1Current\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"West\"}))"
    },
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PV2Current\" or r[\"_field\"] == \"PV3Current\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \"East\": (r.PV2Current + r.PV3Current) }))\n  |> keep(columns:[\"_time\", \"East\"])"
    }
   ]
  },
  {
   "title": "Cumulative Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DailyEnergy\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Energy\"}))\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ACVoltage\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"AC Voltage\"}))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ACFrequency\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "AC Current",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar_stats/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ACCurrent\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}